//
//  FavoriteHeroesInteractor.swift
//  MarvelHeroes
//
//  Created by Israel on 13/06/20.
//  Copyright (c) 2020 israel3D. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates and
//  edited by Israel Mesquita.
//  So you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FavoriteHeroesBusinessLogic {
    func doSomething(request: FavoriteHeroes.Something.Request)
}

protocol FavoriteHeroesDataStore {
    //var name: String { get set }
}

class FavoriteHeroesInteractor: FavoriteHeroesBusinessLogic, FavoriteHeroesDataStore {
    
    var presenter: FavoriteHeroesPresentationLogic?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: FavoriteHeroes.Something.Request) {
        let worker = FavoriteHeroesWorker()
        worker.doSomeWork()
        
        let response = FavoriteHeroes.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
