//
//  HeroesInteractor.swift
//  MarvelHeroes
//
//  Created by Israel on 13/06/20.
//  Copyright (c) 2020 israel3D. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates and
//  edited by Israel Mesquita.
//  So you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HeroesBusinessLogic {
    func doSomething(request: Heroes.Something.Request)
}

protocol HeroesDataStore {
    //var name: String { get set }
}

class HeroesInteractor: HeroesBusinessLogic, HeroesDataStore {
    
    var presenter: HeroesPresentationLogic?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: Heroes.Something.Request) {
        let worker = HeroesWorker()
        worker.doSomeWork()
        
        let response = Heroes.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
