//
//  HeroesPresenter.swift
//  MarvelHeroes
//
//  Created by Israel on 13/06/20.
//  Copyright (c) 2020 israel3D. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates and
//  edited by Israel Mesquita.
//  So you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HeroesPresentationLogic {
    func presentSomething(response: Heroes.Something.Response)
}

class HeroesPresenter: HeroesPresentationLogic {
    
    weak var viewController: HeroesDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: Heroes.Something.Response) {
        let viewModel = Heroes.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
